name: Semver
description: Substitute variables for JSON/XML - first release will support JSON
inputs:
  repo:
    required: false
    default: ${{ github.repository }}
  token:
    required: false
    default: ${{ github.token }}  
  action:
    required: true
    default: 'PATCH' 
  
  
outputs:
  artifacts:
    description: artifacts
runs:
  using: "node16"
  main: src/index.js
